services:
  frontend:
    image: ghcr.io/tanuj-b/recruiter-copilot:production
    container_name: recruiter-copilot-frontend
    ports:
      - "80:80"  # Production uses port 80
    environment:
    
      # API Configuration - ALL REQUIRED for production
      # These MUST be set explicitly - no defaults allowed
      VITE_API_BASE_URL: https://api.example.com/api/v1  # CHANGE THIS to your production API
      VITE_API_TIMEOUT: 30000
      VITE_API_RETRY_ATTEMPTS: 3
      VITE_API_RETRY_DELAY: 1000
      
      # Feature Flags - REQUIRED
      VITE_ENABLE_CSV_EXPORT: "true"
      VITE_ENABLE_BULK_ACTIONS: "true"
      
      # Production should NOT use these test flags
      # VITE_SKIP_AUTH: "false"  # DO NOT SET IN PRODUCTION
      # VITE_MOCK_USER_ID: ""    # DO NOT SET IN PRODUCTION
    
    restart: always
    
    # Health check for production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M